zeroeightysix/KAMI

- src/main/java/me/zeroeightsix/kami/module/modules/combat/CrystalAura.java
Fixed various flags from NCP due to large packet flows and incorrect attacking times with CrystalAura
> CrystalAura Improvements

- src/main/java/me/zeroeightsix/kami/module/modules/combat/CrystalAura.java
Fixed a visual bug with crystals in the hotbar caused by a miscommunication with the server. Sorry.
> oopsies i made a bug

- src/main/java/me/zeroeightsix/kami/module/modules/render/NoHurtCam.java
> Fix NoHurtCam crash

- build.gradle
- src/main/java/me/zeroeightsix/kami/KamiMod.java
- src/main/java/me/zeroeightsix/kami/event/KamiEvent.java
- src/main/java/me/zeroeightsix/kami/module/Module.java
- src/main/java/me/zeroeightsix/kami/util/LagCompensator.java
Repositories don't need the name argument, makes the build file a lot more readable.
> Clean gradle

- README.md
> Add issues badge to the readme file

- src/main/java/me/zeroeightsix/kami/command/commands/BindCommand.java
- src/main/java/me/zeroeightsix/kami/gui/kami/component/BindButton.java
- src/main/java/me/zeroeightsix/kami/module/Module.java
- src/main/java/me/zeroeightsix/kami/module/ModuleManager.java
- src/main/java/me/zeroeightsix/kami/module/modules/ClickGUI.java
- src/main/java/me/zeroeightsix/kami/module/modules/movement/Sprint.java
- src/main/java/me/zeroeightsix/kami/setting/SettingsClass.java
- src/main/java/me/zeroeightsix/kami/util/Bind.java
This PR allows modules to be bound to keys with modifiers. (e.g. Ctrl + Shift + S)
See #36
> Binds with key modifiers

- README.md
Update the building section in README to include the new added `autobuild.bat`
If @wine could also add a section on how to use `autobuild` with `*nix` that would be great.
> Update Building section to include new autobuild

- LICENSE
- README.md
Basically we don't want another Sliz_D_2017 (forking and releasing the whole thing under their name basically without giving credit or disclosing source or stating changes), and the line in the README that says "it isn't ready for release" can be confusing, since there *are* releases available.
> Add a License and update readme, since there are obviously releases out.

- build.gradle
- src/main/java/me/zeroeightsix/kami/command/commands/PathCommand.java
Baritone no longer crashes or fails to compile. It also no longer uses the "hacky" fixed I used over the weekend.
> Fix baritone to prevent mixin crashing and compile errs

- src/main/java/me/zeroeightsix/kami/module/modules/player/PortalGodMode.java
Title says it all, see the diff
> Fix poor formatting in PortalGodMode

- src/main/java/me/zeroeightsix/kami/module/modules/player/Blink.java
Took the cloned player code from freecam and put it into blink. My coding isn't great and it probably has a lot of unnecessary and dumb stuff, but most of the code wasn't made by me, so it actually does work. Unlike most things I make 😎.
> Added a cloned player model to blink

- src/main/java/me/zeroeightsix/kami/module/modules/combat/Aura.java
- src/main/java/me/zeroeightsix/kami/module/modules/combat/CrystalAura.java
> 32k Aura and Anti Weakness Crystals

- src/main/java/me/zeroeightsix/kami/module/modules/combat/Aura.java
- src/main/java/me/zeroeightsix/kami/module/modules/combat/Auto32k.java
Added Auto32k, also fixed a Bug in Aura Raytracing Check:
old:  ```...new Vec3d(mc.player.posX, mc.player.posX + mc.player.getEyeHeight()...```
new: ```...new Vec3d(mc.player.posX, mc.player.posY + mc.player.getEyeHeight()...```
in commit [c895b89e0e0737049c9c6bb27090eadf6758a33d](https://github.com/blockparole/KAMI/commit/c895b89e0e0737049c9c6bb27090eadf6758a33d)
> Auto32k & Aura Bugfix

- src/main/java/me/zeroeightsix/kami/module/Module.java
Backpoort of cookiedragon234s [fix](https://github.com/S-B99/KAMI/pull/46).
> Fix: Multiple Sprint Modules

- src/main/java/me/zeroeightsix/kami/module/modules/misc/AutoRespawn.java
added a fix for death screen glitch, opening in pvp while still alive.
> added AutoRespawn anti glitch feature

- src/main/java/me/zeroeightsix/kami/module/modules/movement/IceSpeed.java
It uses `Setting<Double>` cause of this [problem](https://github.com/zeroeightysix/KAMI/issues/145).
> added IceSpeed

- src/main/java/me/zeroeightsix/kami/module/modules/combat/FastBow.java
Kami Blue also [has it](https://github.com/S-B99/KAMI/blob/features-master/src/main/java/me/zeroeightsix/kami/module/modules/sdashb/combat/BowSpam.java), so i figured i could add it here too.
> added seppukus FastBow

- src/main/java/me/zeroeightsix/kami/module/modules/combat/Auto32k.java
- src/main/java/me/zeroeightsix/kami/module/modules/combat/AutoFeetPlace.java
- src/main/java/me/zeroeightsix/kami/module/modules/player/Scaffold.java
- src/main/java/me/zeroeightsix/kami/util/BlockInteractionHelper.java
added AutoFeetPlace
moved some block placing related code to BlockInteractionHelper, to be shared between modules
> added AutoFeetPlace

- docs/TROUBLESHOOTING.md
I had someone in my discord experience this, would be good to document it
> Added more troubleshooting information for building

- src/main/java/me/zeroeightsix/kami/module/modules/player/FastExp.java
Added fastexp with autoswitch and autothrow settings.
> added FastExp

- src/main/java/me/zeroeightsix/kami/module/modules/player/AutoReplenish.java
refills the players hotbarslots from inventory
> AutoReplenish

- src/main/java/me/zeroeightsix/kami/module/modules/misc/AntiSpam.java
This adds a basic regex based antispam module.
> Chat AntiSpam

- src/main/java/me/zeroeightsix/kami/module/modules/misc/VisualRange.java
Surprisingly, a lot of people prefer this over the text radar.
> VisualRange
